[msg GameShow1_ANS_F]
[s][f 3 1 1 0 0 0]> You got the answer correct![n][f 1 3 65535][w][e]

[msg GameShow1_ANS_T]
[s][f 3 1 1 0 0 0]> You got the answer wrong....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 0]> You turn off the TV....[n][f 1 3 65535][w][e]

[msg GameShow1_ANS_Academics]
[s][f 3 1 1 0 0 0]> You feel slightly smarter.[n][f 1 3 65535][w][e]

[msg GameShow1_ANS_Courage]
[s][f 3 1 1 0 0 0]> You feel slightly braver.[n][f 1 3 65535][w][e]

[msg GameShow1_ANS_Charm]
[s][f 3 1 1 0 0 0]> You feel slightly more charming.[n][f 1 3 65535][w][e

[msg AlreadyWatchedToday]
[s][f 3 1 1 0 0 0]> You already tried today.[n][f 1 3 65535][w][e]

[msg BORINGTV]
[s][f 3 1 1 0 0 0]> There's nothing interesting on.[n][f 1 3 65535][w][e]

[msg OHLOOKTHERES]
[s][f 3 1 1 0 0 0]> There's a game show playing on TV.[n][f 1 3 65535][w][e]